kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-clusterip
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app: {{lower .Release.Name}}