kind: Service
apiVersion: v1
metadata:
  name: {{lower .Release.Name}}-clusterip
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{lower .Release.Name}}