kind: Service
apiVersion: v1
metadata:
  name: {{lower .Release.Name}}-loadbalancer
  annotations:
    {{- if .Values.service.loadbalancer.isMetalLb}}
    metallb.universe.tf/loadBalancerIPs: {{.Values.service.loadbalancer.ip}}
    metallb.universe.tf/allow-shared-ip: antennas
    {{- end}}
    {{- if .Values.service.loadbalancer.isCilium}}
    io.cilium/lb-ipam-ips: {{.Values.service.loadbalancer.ip}}
    io.cilium/lb-ipam-sharing-key: antennas
    {{- end}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{lower .Release.Name}}
  externalTrafficPolicy: {{ .Values.service.loadbalancer.externalTrafficPolicy }}
  type: LoadBalancer