apiVersion: v1
kind: Secret
metadata:
  name: {{lower .Release.Name}}-secret
stringData:
  PHOTOPRISM_ADMIN_USER: "{{ .Values.environment.photoprismAdminUser }}"
  PHOTOPRISM_ADMIN_PASSWORD: "{{ .Values.environment.photoprismAdminPassword }}"
  PHOTOPRISM_DATABASE_PASSWORD: "{{ .Values.environment.photoprismDatabasePassword }}"
  