kind: Service
apiVersion: v1
metadata:
  name: {{lower .Release.Name}}-loadbalancer
  annotations:
    {{- if .Values.service.loadbalancer.isMetalLb}}
    metallb.universe.tf/loadBalancerIPs: {{.Values.service.loadbalancer.ip}}
    metallb.universe.tf/allow-shared-ip: photoprism
    {{- end}}
    {{- if .Values.service.loadbalancer.isCilium}}
    io.cilium/lb-ipam-ips: {{.Values.service.loadbalancer.ip}}
    io.cilium/lb-ipam-sharing-key: photoprism
    {{- end}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 2342
      targetPort: 2342
  selector:
    app: {{lower .Release.Name}}
  externalTrafficPolicy: {{.Values.service.loadbalancer.externalTrafficPolicy}}
  type: LoadBalancer