apiVersion: v1
kind: Secret
metadata:
  name: kanboard-email-configuration-secret
type: Opaque
stringData:
  MAIL_SMTP_USERNAME: "{{.Values.configuration.emailConfiguration.username}}"
  MAIL_SMTP_PASSWORD: "{{.Values.configuration.emailConfiguration.password}}"