apiVersion: v1
kind: ConfigMap
metadata:
  name: kanboard-http-client
data:
  HTTP_PROXY_HOSTNAME: "{{.Values.configuration.httpClient.proxyHostname}}"
  HTTP_PROXY_PORT: "{{.Values.configuration.httpClient.proxyPort}}"
  HTTP_PROXY_EXCLUDE: "{{.Values.configuration.httpClient.proxyExclude}}"
  HTTP_VERIFY_SSL_CERTIFICATE: "true"