apiVersion: v1
kind: Secret
metadata:
  name: kanboard-http-client-secret
type: Opaque
stringData:
  HTTP_PROXY_USERNAME: "{{.Values.configuration.httpClient.username}}"
  HTTP_PROXY_PASSWORD: "{{.Values.configuration.httpClient.password}}"
