deployment:
  sleepStart: false
  image:
    location: gitea/gitea
    tag: 1.22.6-rootless

pvc:
  data:
    accessMode: ReadWriteMany
    #only applied when set
    storageClass:
    #size in Gi
    storageSize: 5
  config:
    accessMode: ReadWriteMany
    #only applied when set
    storageClass:
    #size in Gi
    storageSize: 5

ingresses:
  - enabled: false
    ingressClassName: nginx
    hostname: gitea.local.lan
    annotations: {}
      # cert-manager.io/cluster-issuer: selfsigned-issuer
  - enabled: false
    ingressClassName: nginx
    hostname: gitea.lan
    annotations: {}
      # cert-manager.io/cluster-issuer: selfsigned-issuer

service:
  loadbalancerIp: "127.0.0.1" #overlay me

configuration:
  databaseType: "postgres"
  databaseHost: "overlay_me"
  databaseName: "overlay_me"
  databaseUser: "overlay_me"
  databasePassword: "overlay_me"
  disableRegistration: "true"
