{{- if .Values.service.loadbalancer.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: authelia-loadbalancer
  annotations:
    {{- if .Values.service.loadbalancer.isMetalLb}}
    metallb.universe.tf/loadBalancerIPs: {{.Values.service.loadbalancer.ip}}
    metallb.universe.tf/allow-shared-ip: authelia
    {{- end}}
    {{- if .Values.service.loadbalancer.isCilium}}
    io.cilium/lb-ipam-ips: {{.Values.service.loadbalancer.ip}}
    io.cilium/lb-ipam-sharing-key: authelia
    {{- end}}
spec:
  type: LoadBalancer
  selector: {{- include "authelia.matchLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
{{- end }}