apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-nexus-data
  labels:
    app: {{.Release.Name}}-nexus
spec:
  accessModes:
    - {{.Values.storage.data.accessMode}}
  storageClassName: {{.Values.storage.data.storageClassName}}
  resources:
    requests:
      storage: {{.Values.storage.data.storageRequest}}Gi