apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-data
spec:
  accessModes:
    - {{ .Values.pvc.data.accessMode }}
  {{ if .Values.pvc.data.storageClass }}
  storageClassName: {{ .Values.pvc.data.storageClass }}
  {{ end}}
  resources:
    requests:
      storage: {{ .Values.pvc.data.storageSize }}Gi