apiVersion: v1
kind: Service
metadata:
  name: kanboard-clusterip
spec:
  type: ClusterIP
  selector:
    app: kanboard
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80