deployment:
  #sleepstart is useful when you want to recreate a configuration within the pod - default should be "false"
  sleepStart: false
  image:
    location: ghcr.io/element-hq/synapse
    tag: v1.114.0
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 1000Mi
    # requests:
    #   cpu: 100m
    #   memory: 500Mi

pvc:
  data:
    accessMode: ReadWriteMany
    storageClass: #only applied when set
    storageSize: 5 #size in Gi

service: 
  loadbalancerIp:
    ip: 127.0.0.1

configuration:
  serverName: "overlay_me"
  reportStats: "true"
  configPath: "/config/homeserver.yaml"
  unsafeLocale: "true"

homeserverConfiguration: |-
  "overlay_me"

logConfiguration: |-
  version: 1
  formatters:
    precise:
      format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
  handlers:
    file:
      class: logging.handlers.TimedRotatingFileHandler
      formatter: precise
      filename: /tmp/homeserver.log
      when: midnight
      backupCount: 1  # Does not include the current log file.
      encoding: utf8
    buffer:
      class: synapse.logging.handlers.PeriodicallyFlushingMemoryHandler
      target: file
      capacity: 10
      flushLevel: 30  # Flush immediately for WARNING logs and higher
      period: 5
    console:
      class: logging.StreamHandler
      formatter: precise
  loggers:
    synapse.storage.SQL:
      level: INFO
  root:
      level: INFO
      handlers: [buffer]
  disable_existing_loggers: false