apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-configuration
data:
  ATUIN_DB_USERNAME: "{{ .Values.configuration.dbUsername }}"
  ATUIN_HOST: "{{ .Values.configuration.host }}"
  ATUIN_PORT: "8888"
  ATUIN_OPEN_REGISTRATION: "{{ .Values.configuration.openRegistration }}"