apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secret-configuration
type: Opaque
stringData:
  ATUIN_DB_URI: "{{ .Values.secret.dbUri }}"
  ATUIN_DB_PASSWORD: "{{ .Values.secret.dbPassword }}"