name: Release Charts

on:
  push:
    tags: ['*']

# permissions are needed if pushing to ghcr.io
permissions: 
  packages: write

jobs:
  release:     
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"