apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-configuration
data:
  USER_UID: "1000"
  USER_GID: "1000"
  GITEA__database__DB_TYPE: "{{ .Values.configuration.databaseType }}"
  GITEA__database__HOST: "{{ .Values.configuration.databaseHost }}"
  GITEA__database__NAME: "{{ .Values.configuration.databaseName }}"
  GITEA__database__USER: "{{ .Values.configuration.databaseUser }}"
  GITEA__database__PASSWD: "{{ .Values.configuration.databasePassword }}"
  DISABLE_REGISTRATION: "{{ .Values.configuration.disableRegistration }}"
  SSH_PORT: "60000"
  GITEA__webhook__ALLOWED_HOST_LIST: "private,loopback"
  GITEA__webhook__SKIP_TLS_VERIFY: "true"
