kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-lb
spec:
  ports:
    - name: http
      port: 3000
    - name: ssh
      port: 60000
  selector:
    app: gitea
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.loadbalancerIp }}
  type: LoadBalancer